"""Fix circular import and backref conflict for achievements

Revision ID: 9e4bbe1a527c
Revises: 
Create Date: 2025-04-05 04:44:44.806056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e4bbe1a527c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True))
        batch_op.alter_column('sender_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        
        # Add explicit names to the foreign key constraints
        batch_op.create_foreign_key('fk_message_conversation', 'conversations', ['conversation_id'], ['id'])
        batch_op.create_foreign_key('fk_message_group', 'groups', ['group_id'], ['id'])
        batch_op.create_foreign_key('fk_message_recipient', 'users', ['recipient_id'], ['id'])
        batch_op.create_foreign_key('fk_message_sender', 'users', ['sender_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint('fk_message_conversation', type_='foreignkey')
        batch_op.drop_constraint('fk_message_group', type_='foreignkey')
        batch_op.drop_constraint('fk_message_recipient', type_='foreignkey')
        batch_op.drop_constraint('fk_message_sender', type_='foreignkey')
        batch_op.alter_column('sender_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('group_id')
        batch_op.drop_column('recipient_id')

    # ### end Alembic commands ###
